"""latest

Revision ID: 1fc6dd63a283
Revises:
Create Date: 2025-11-16 17:43:51.791710

"""

from typing import Sequence, Union

import sqlmodel.sql.sqltypes
import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1fc6dd63a283"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Enable pg_trgm extension
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")

    op.create_table(
        "titles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("cover", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("name_en", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("name_ru", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("alt_names", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "type_",
            sa.Enum(
                "MANGA",
                "NOVEL",
                "LIGHT_NOVEL",
                "ONESHOT",
                "DOUJIN",
                "MANHWA",
                "MANHUA",
                "COMICS",
                "WEBTOON",
                "OTHER",
                name="titletype",
            ),
            nullable=False,
        ),
        sa.Column("chapters", sa.Integer(), nullable=False),
        sa.Column("volumes", sa.Integer(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("in_app_rating", sa.Float(), nullable=True),
        sa.Column("in_app_scored_by", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "ONGOING",
                "FINISHED",
                "DISCONTINUED",
                "LICENSED",
                "FROZEN",
                "ANONS",
                "UNKNOWN",
                name="titlestatus",
            ),
            nullable=False,
        ),
        sa.Column("date", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("scored_by", sa.Integer(), nullable=False),
        sa.Column("popularity", sa.Integer(), nullable=False),
        sa.Column("favorites", sa.Integer(), nullable=False),
        sa.Column(
            "description", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("authors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "genres",
            postgresql.ARRAY(
                sa.Enum(
                    "ACTION",
                    "ADVENTURE",
                    "AVANT_GARDE",
                    "AWARD_WINNING",
                    "GENDER_INTRIGUE",
                    "HEROIC_FANTASY",
                    "BOYS_LOVE",
                    "COMEDY",
                    "DRAMA",
                    "COMBAT",
                    "HUMOR",
                    "MURIM",
                    "SCHOOL_LIFE",
                    "FANTASTIC",
                    "THRILLER",
                    "TRAGEDY",
                    "PSYCHOLOGY",
                    "POST_APOCALYPTIC",
                    "ELEMENTS_OF_HUMOR",
                    "KODOMO",
                    "KIDS",
                    "CYBERPUNK",
                    "HISTORY",
                    "FANTASY",
                    "GIRLS_LOVE",
                    "GOURMET",
                    "HORROR",
                    "MYSTERY",
                    "ROMANCE",
                    "SCI_FI",
                    "SLICE_OF_LIFE",
                    "SPORTS",
                    "SUPERNATURAL",
                    "SUSPENSE",
                    "SEINEN",
                    "SHOUNEN",
                    "DOUJINSHI",
                    "SHOUJO",
                    "JOSEI",
                    "YAOI",
                    "ECCHI",
                    "EROTICA",
                    "HENTAI",
                    "ADULT_CAST",
                    "ANTHROPOMORPHIC",
                    "CGDCT",
                    "CHILDCARE",
                    "COMBAT_SPORTS",
                    "CROSSDRESSING",
                    "DELINQUENTS",
                    "DETECTIVE",
                    "EDUCATIONAL",
                    "GAG_HUMOR",
                    "GORE",
                    "HAREM",
                    "HIGH_STAKES_GAME",
                    "HISTORICAL",
                    "IDOLS_FEMALE",
                    "IDOLS_MALE",
                    "ISEKAI",
                    "IYASHIKEI",
                    "LOVE_POLYGON",
                    "LOVE_STATUS_QUO",
                    "MAGICAL_SEX_SHIFT",
                    "MAHOU_SHOUJO",
                    "MARTIAL_ARTS",
                    "MECHA",
                    "MEDICAL",
                    "MEMOIR",
                    "MILITARY",
                    "MUSIC",
                    "MYTHOLOGY",
                    "ORGANIZED_CRIME",
                    "OTAKU_CULTURE",
                    "PARODY",
                    "PERFORMING_ARTS",
                    "PETS",
                    "PSYCHOLOGICAL",
                    "RACING",
                    "REINCARNATION",
                    "REVERSE_HAREM",
                    "SAMURAI",
                    "SCHOOL",
                    "SHOWBIZ",
                    "SPACE",
                    "STRATEGY_GAME",
                    "SUPER_POWER",
                    "SURVIVAL",
                    "TEAM_SPORTS",
                    "TIME_TRAVEL",
                    "URBAN_FANTASY",
                    "VAMPIRE",
                    "VIDEO_GAME",
                    "VILLAINESS",
                    "VISUAL_ARTS",
                    "WORKPLACE",
                    "UNKNOWN",
                    name="titlegenre",
                )
            ),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("data_quality_score", sa.Float(), nullable=False),
        sa.Column(
            "primary_source",
            sa.Enum("MAL", "REMANGA", "SHIKIMORI", "CUSTOM", name="sourceprovider"),
            nullable=True,
        ),
        sa.Column(
            "extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_title_alt_names_gin",
        "titles",
        ["alt_names"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_title_extra_data_gin",
        "titles",
        ["extra_data"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_title_name_en_trigram",
        "titles",
        ["name_en"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name_en": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_title_name_ru_trigram",
        "titles",
        ["name_ru"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name_ru": "gin_trgm_ops"},
    )
    op.create_index(
        "idx_title_rating_scored_by", "titles", ["rating", "scored_by"], unique=False
    )
    op.create_index(
        "idx_title_search_vector",
        "titles",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_title_type_status", "titles", ["type_", "status"], unique=False
    )
    op.create_index(
        "idx_title_type_status_rating",
        "titles",
        ["type_", "status", "rating"],
        unique=False,
    )
    op.create_index(op.f("ix_titles_chapters"), "titles", ["chapters"], unique=False)
    op.create_index(op.f("ix_titles_genres"), "titles", ["genres"], unique=False)
    op.create_index(op.f("ix_titles_id"), "titles", ["id"], unique=False)
    op.create_index(
        op.f("ix_titles_popularity"), "titles", ["popularity"], unique=False
    )
    op.create_index(op.f("ix_titles_rating"), "titles", ["rating"], unique=False)
    op.create_index(op.f("ix_titles_scored_by"), "titles", ["scored_by"], unique=False)
    op.create_index(op.f("ix_titles_status"), "titles", ["status"], unique=False)
    op.create_index(op.f("ix_titles_type_"), "titles", ["type_"], unique=False)
    op.create_index(op.f("ix_titles_views"), "titles", ["views"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False
        ),
        sa.Column(
            "email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("google_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("yandex_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("avatar", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("avg_rating", sa.Float(), nullable=False),
        sa.Column("count_likes", sa.Integer(), nullable=False),
        sa.Column("count_votes", sa.Integer(), nullable=False),
        sa.Column("count_comments", sa.Integer(), nullable=False),
        sa.Column(
            "count_bookmarks", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "description", sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True
        ),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "registration_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_google_id"), "users", ["google_id"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_index(op.f("ix_users_yandex_id"), "users", ["yandex_id"], unique=False)
    op.create_table(
        "title_source_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("master_title_id", sa.Integer(), nullable=True),
        sa.Column(
            "source_provider",
            sa.Enum("MAL", "REMANGA", "SHIKIMORI", "CUSTOM", name="sourceprovider"),
            nullable=False,
        ),
        sa.Column(
            "source_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "source_url", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True
        ),
        sa.Column("raw_data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "consolidation_status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "CONSOLIDATED",
                "FAILED",
                name="consolidationstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_verified_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted_from_source", sa.Boolean(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parse_error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["master_title_id"],
            ["titles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_source_data_deleted",
        "title_source_data",
        ["is_deleted_from_source"],
        unique=False,
        postgresql_where=sa.text("is_deleted_from_source = true"),
    )
    op.create_index(
        "idx_source_data_mal_id",
        "title_source_data",
        [sa.literal_column("jsonb_extract_path_text(raw_data, 'mal_id')")],
        unique=False,
    )
    op.create_index(
        "idx_source_data_pending",
        "title_source_data",
        ["consolidation_status", "fetched_at"],
        unique=False,
        postgresql_where=sa.text("consolidation_status = 'PENDING'"),
    )
    op.create_index(
        "idx_source_data_provider_id",
        "title_source_data",
        ["source_provider", "source_id"],
        unique=True,
    )
    op.create_index(
        "idx_source_data_raw_data_gin",
        "title_source_data",
        ["raw_data"],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        "idx_source_data_unmapped",
        "title_source_data",
        ["master_title_id"],
        unique=False,
        postgresql_where=sa.text("master_title_id IS NULL"),
    )
    op.create_index(
        op.f("ix_title_source_data_consolidation_status"),
        "title_source_data",
        ["consolidation_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_title_source_data_fetched_at"),
        "title_source_data",
        ["fetched_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_title_source_data_id"), "title_source_data", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_title_source_data_is_deleted_from_source"),
        "title_source_data",
        ["is_deleted_from_source"],
        unique=False,
    )
    op.create_index(
        op.f("ix_title_source_data_master_title_id"),
        "title_source_data",
        ["master_title_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_title_source_data_source_id"),
        "title_source_data",
        ["source_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_title_source_data_source_provider"),
        "title_source_data",
        ["source_provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_title_source_data_version"),
        "title_source_data",
        ["version"],
        unique=False,
    )
    op.create_table(
        "user_titles",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("user_rating", sa.Integer(), nullable=False),
        sa.Column("current_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "bookmark",
            sa.Enum(
                "NOT_READING",
                "READING",
                "COMPLETED",
                "DROPPED",
                "PLANNED",
                name="bookmarktype",
            ),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("extra_data", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["titles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "title_id"),
    )
    op.create_index(
        op.f("ix_user_titles_title_id"), "user_titles", ["title_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_titles_user_id"), "user_titles", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_titles_user_id"), table_name="user_titles")
    op.drop_index(op.f("ix_user_titles_title_id"), table_name="user_titles")
    op.drop_table("user_titles")
    op.drop_index(op.f("ix_title_source_data_version"), table_name="title_source_data")
    op.drop_index(
        op.f("ix_title_source_data_source_provider"), table_name="title_source_data"
    )
    op.drop_index(
        op.f("ix_title_source_data_source_id"), table_name="title_source_data"
    )
    op.drop_index(
        op.f("ix_title_source_data_master_title_id"), table_name="title_source_data"
    )
    op.drop_index(
        op.f("ix_title_source_data_is_deleted_from_source"),
        table_name="title_source_data",
    )
    op.drop_index(op.f("ix_title_source_data_id"), table_name="title_source_data")
    op.drop_index(
        op.f("ix_title_source_data_fetched_at"), table_name="title_source_data"
    )
    op.drop_index(
        op.f("ix_title_source_data_consolidation_status"),
        table_name="title_source_data",
    )
    op.drop_index(
        "idx_source_data_unmapped",
        table_name="title_source_data",
        postgresql_where=sa.text("master_title_id IS NULL"),
    )
    op.drop_index(
        "idx_source_data_raw_data_gin",
        table_name="title_source_data",
        postgresql_using="gin",
    )
    op.drop_index("idx_source_data_provider_id", table_name="title_source_data")
    op.drop_index(
        "idx_source_data_pending",
        table_name="title_source_data",
        postgresql_where=sa.text("consolidation_status = 'PENDING'"),
    )
    op.drop_index("idx_source_data_mal_id", table_name="title_source_data")
    op.drop_index(
        "idx_source_data_deleted",
        table_name="title_source_data",
        postgresql_where=sa.text("is_deleted_from_source = true"),
    )
    op.drop_table("title_source_data")
    op.drop_index(op.f("ix_users_yandex_id"), table_name="users")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_google_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_titles_views"), table_name="titles")
    op.drop_index(op.f("ix_titles_type_"), table_name="titles")
    op.drop_index(op.f("ix_titles_status"), table_name="titles")
    op.drop_index(op.f("ix_titles_scored_by"), table_name="titles")
    op.drop_index(op.f("ix_titles_rating"), table_name="titles")
    op.drop_index(op.f("ix_titles_popularity"), table_name="titles")
    op.drop_index(op.f("ix_titles_id"), table_name="titles")
    op.drop_index(op.f("ix_titles_genres"), table_name="titles")
    op.drop_index(op.f("ix_titles_chapters"), table_name="titles")
    op.drop_index("idx_title_type_status_rating", table_name="titles")
    op.drop_index("idx_title_type_status", table_name="titles")
    op.drop_index(
        "idx_title_search_vector", table_name="titles", postgresql_using="gin"
    )
    op.drop_index("idx_title_rating_scored_by", table_name="titles")
    op.drop_index(
        "idx_title_name_ru_trigram",
        table_name="titles",
        postgresql_using="gin",
        postgresql_ops={"name_ru": "gin_trgm_ops"},
    )
    op.drop_index(
        "idx_title_name_en_trigram",
        table_name="titles",
        postgresql_using="gin",
        postgresql_ops={"name_en": "gin_trgm_ops"},
    )
    op.drop_index(
        "idx_title_extra_data_gin", table_name="titles", postgresql_using="gin"
    )
    op.drop_index(
        "idx_title_alt_names_gin", table_name="titles", postgresql_using="gin"
    )
    op.drop_table("titles")

    op.execute("DROP EXTENSION IF EXISTS pg_trgm")
    # ### end Alembic commands ###
