"""initial

Revision ID: 6849ebfbcf6b
Revises: 
Create Date: 2025-07-04 18:49:10.538805

"""
from typing import Sequence, Union

import sqlmodel.sql.sqltypes
import sqlalchemy as sa

from alembic import op

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6849ebfbcf6b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('cover', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alt_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('type_', sa.Enum('MANGA', 'NOVEL', 'LIGHT_NOVEL', 'ONESHOT', 'DOUJIN', 'MANHWA', 'MANHUA', 'WEBTOON', 'OTHER', name='titletype'), nullable=False),
    sa.Column('chapters', sa.Integer(), nullable=False),
    sa.Column('volumes', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('in_app_rating', sa.Float(), nullable=True),
    sa.Column('in_app_scored_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ONGOING', 'FINISHED', 'DISCONTINUED', 'FROZEN', 'ANONS', 'UNKNOWN', name='titlestatus'), nullable=False),
    sa.Column('date', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('scored_by', sa.Integer(), nullable=False),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.Column('favorites', sa.Integer(), nullable=False),
    sa.Column('description', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('genres', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_provider', sa.Enum('MAL', 'REMANGA', 'SHIKIMORI', 'CUSTOM', name='sourceprovider'), nullable=False),
    sa.Column('source_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titles_genres'), 'titles', ['genres'], unique=False)
    op.create_index(op.f('ix_titles_id'), 'titles', ['id'], unique=False)
    op.create_index(op.f('ix_titles_search_vector'), 'titles', ['search_vector'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_titles_search_vector'), table_name='titles')
    op.drop_index(op.f('ix_titles_id'), table_name='titles')
    op.drop_index(op.f('ix_titles_genres'), table_name='titles')
    op.drop_table('titles')
    # ### end Alembic commands ###
