"""added kids genre

Revision ID: 6891ee798f10
Revises: 7711c81abab3
Create Date: 2025-07-08 01:08:52.156389

"""
from typing import Sequence, Union

import sqlmodel.sql.sqltypes
import sqlalchemy as sa

from alembic import op



# revision identifiers, used by Alembic.
revision: str = '6891ee798f10'
down_revision: Union[str, None] = '7711c81abab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE titlegenre ADD VALUE 'KIDS'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
