"""added_new_enum_fields

Revision ID: 7711c81abab3
Revises: f6a5915ac87c
Create Date: 2025-07-07 19:12:59.608022

"""
from typing import Sequence, Union

import sqlmodel.sql.sqltypes
import sqlalchemy as sa

from alembic import op



# revision identifiers, used by Alembic.
revision: str = '7711c81abab3'
down_revision: Union[str, None] = 'f6a5915ac87c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE titlestatus ADD VALUE 'LICENSED'")
    op.execute("ALTER TYPE titletype ADD VALUE 'COMICS'")
    op.alter_column('titles', 'source_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('titles', 'source_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
