"""Initial tables

Revision ID: bed2f1a745ad
Revises:
Create Date: 2025-04-10 20:57:35.867358

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "bed2f1a745ad"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "manga",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("source_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("alt_names", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("avg_rating", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("chapters", sa.Integer(), nullable=False),
        sa.Column("cover", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "translate_status", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("genres", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("categories", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_update", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_manga_id"), "manga", ["id"], unique=False)
    op.create_table(
        "user",
        sa.Column(
            "username", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False
        ),
        sa.Column(
            "hashed_password", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("recovery_code", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("registration_date", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("username"),
    )
    op.create_index(op.f("ix_user_username"), "user", ["username"], unique=True)
    op.create_table(
        "usermanga",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("manga_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("current_url", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "section",
            sa.Enum(
                "READING", "PLANNED", "COMPLETED", "NOT_READ", "ANY", name="section"
            ),
            nullable=False,
        ),
        sa.Column("last_read", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["manga_id"],
            ["manga.id"],
        ),
        sa.ForeignKeyConstraint(
            ["username"],
            ["user.username"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_usermanga_manga_id"), "usermanga", ["manga_id"], unique=False
    )
    op.create_index(
        op.f("ix_usermanga_username"), "usermanga", ["username"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usermanga_username"), table_name="usermanga")
    op.drop_index(op.f("ix_usermanga_manga_id"), table_name="usermanga")
    op.drop_table("usermanga")
    op.drop_index(op.f("ix_user_username"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_manga_id"), table_name="manga")
    op.drop_table("manga")
    # ### end Alembic commands ###
