"""update_genre_type

Revision ID: f6a5915ac87c
Revises: 36924eefd562
Create Date: 2025-07-07 02:37:43.531109

"""
from typing import Sequence, Union

import sqlmodel.sql.sqltypes
import sqlalchemy as sa

from alembic import op



# revision identifiers, used by Alembic.
revision: str = 'f6a5915ac87c'
down_revision: Union[str, None] = '36924eefd562'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
