"""add_composite_search_indexes

Revision ID: 4a6ff30a20a5
Revises: de0d04f9eb90
Create Date: 2026-03-10 19:00:50.577029

"""
from typing import Sequence, Union

import sqlmodel.sql.sqltypes
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4a6ff30a20a5'
down_revision: Union[str, Sequence[str], None] = 'de0d04f9eb90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_titles_status_type_rating', 'titles', ['status', 'type', sa.literal_column('rating DESC')], unique=False, postgresql_where=sa.text('is_deleted = FALSE'))
    op.create_index('ix_titles_type_rating', 'titles', ['type', sa.literal_column('rating DESC')], unique=False, postgresql_where=sa.text('is_deleted = FALSE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_titles_type_rating', table_name='titles', postgresql_where=sa.text('is_deleted = FALSE'))
    op.drop_index('ix_titles_status_type_rating', table_name='titles', postgresql_where=sa.text('is_deleted = FALSE'))
    # ### end Alembic commands ###
