"""init

Revision ID: 6b7b8c5ba6cc
Revises: 
Create Date: 2026-01-23 19:27:32.792014

"""
from typing import Sequence, Union

import sqlmodel.sql.sqltypes
import sqlalchemy as sa

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b7b8c5ba6cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mal_id', sa.Integer(), nullable=True),
    sa.Column('search_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alt_names', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description_ru', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('popularity', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('scored_by', sa.Integer(), nullable=False),
    sa.Column('chapters', sa.Integer(), nullable=False),
    sa.Column('volumes', sa.Integer(), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('favorites', sa.Integer(), nullable=False),
    sa.Column('genres', postgresql.ARRAY(sa.Enum('ACTION', 'ADVENTURE', 'AVANT_GARDE', 'AWARD_WINNING', 'BOYS_LOVE', 'COMEDY', 'CYBERPUNK', 'DEMOGRAPHY_JOSEI', 'DEMOGRAPHY_KODOMO', 'DEMOGRAPHY_SEINEN', 'DEMOGRAPHY_SHOUJO', 'DEMOGRAPHY_SHOUNEN', 'DETECTIVE', 'DOUJINSHI', 'DRAMA', 'ECCHI', 'EROTICA', 'FANTASY', 'GAG_HUMOR', 'GENDER_BENDER', 'GIRLS_LOVE', 'GOURMET', 'HAREM', 'HENTAI', 'HEROIC_FANTASY', 'HISTORICAL', 'HORROR', 'ISEKAI', 'MAHOU_SHOUJO', 'MARTIAL_ARTS', 'MECHA', 'MURIM', 'MYSTERY', 'POST_APOCALYPTIC', 'PSYCHOLOGICAL', 'ROMANCE', 'SCHOOL_LIFE', 'SCIENCE_FICTION', 'SLICE_OF_LIFE', 'SPORTS', 'STUDENT_LIFE', 'SUPERNATURAL', 'SUSPENSE', 'TRAGEDY', 'UNKNOWN', name='titlegenre')), nullable=True),
    sa.Column('categories', postgresql.ARRAY(sa.Enum('ADULT_CAST', 'ALCHEMY', 'AMNESIA', 'ANGELS', 'ANIME', 'ANTHROPOMORPHIC', 'ANTIHERO', 'ANTHOLOGY', 'APOCALYPSE', 'ARISTOCRACY', 'ARMY', 'ARTIFACTS', 'AWARD_WINNING', 'BEASTMEN', 'BLACKMAIL', 'CGDCT', 'CHILDCARE', 'COMBAT_SPORTS', 'COLORED', 'COOKING', 'CRIME', 'CROSSDRESSING', 'CRUEL_WORLD', 'CULTIVATION', 'DELINQUENTS', 'DEMON_LORD', 'DEMONS', 'DETECTIVE', 'DUNGEONS', 'DYSTOPIA', 'EDUCATIONAL', 'EDUTAINMENT', 'FEMALE_PROTAGONIST', 'FRIENDSHIP', 'FUTURE', 'GAG_HUMOR', 'GAMERS', 'GAME_ELEMENTS', 'GODS', 'GORE', 'GUILDS', 'GYARU', 'HAREM', 'HIDDEN_IDENTITY', 'HIKIKOMORI', 'HIGH_STAKES_GAME', 'HISTORICAL', 'IDOLS_FEMALE', 'IDOLS_MALE', 'INTELLIGENT_RACES', 'ISEKAI', 'ISEKAI_MEMORIES', 'IYASHIKEI', 'KNIGHTS', 'LOLI', 'LOVE_POLYGON', 'LOVE_STATUS_QUO', 'MAFIA', 'MAGIC', 'MAGIC_ACADEMY', 'MAGICAL_CREATURES', 'MAGICAL_SEX_SHIFT', 'MAHOU_SHOUJO', 'MALE_PROTAGONIST', 'MARTIAL_ARTS', 'MECHA', 'MEDICAL', 'MEDIEVAL', 'MAIDS', 'MEMOIR', 'MERCENARIES', 'MILITARY', 'MONSTERS', 'MUSIC', 'MYTHOLOGY', 'NINJA', 'NON_HUMAN_PROTAGONIST', 'OFFICE_WORKERS', 'OTAKU_CULTURE', 'OVERPOWERED_PROTAGONIST', 'PARODY', 'PERFORMING_ARTS', 'PET_COMPANIONS', 'PETS', 'POLICE', 'POLITICS', 'POWER_STRUGGLE', 'PSYCHOLOGICAL', 'RACING', 'RANKS_OF_POWER', 'REINCARNATION', 'REVENGE', 'REVERSE_HAREM', 'ROBOTS', 'SAMURAI', 'SAVING_THE_WORLD', 'SCHOOL', 'SHOWBIZ', 'SINGLE', 'SKILLS', 'SHOUNEN', 'SEINEN', 'SMART_PROTAGONIST', 'SPACE', 'STEAMPUNK', 'STRATEGY_GAME', 'STUPIDITY', 'STUPID_PROTAGONIST', 'SUPER_POWER', 'SUPERHEROES', 'SURVIVAL', 'SWORD_FIGHTING', 'SYSTEM', 'TEACHER_STUDENT', 'TEAM_SPORTS', 'TERRITORY_MANAGEMENT', 'TIME_TRAVEL', 'TRADITIONAL_GAMES', 'TRUCK_KUN', 'UNDEAD', 'JOSEI', 'URBAN_FANTASY', 'VAMPIRE', 'VIDEO_GAME', 'VILLAINESS', 'VIOLENCE', 'VISUAL_ARTS', 'WEB', 'WESTERN', 'WORKPLACE', 'YONKOMA', 'ZOMBIES', 'UNKNOWN', name='titlecategory')), nullable=True),
    sa.Column('authors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cover', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('type', sa.Enum('MANGA', 'NOVEL', 'LIGHT_NOVEL', 'ONESHOT', 'DOUJIN', 'MANHWA', 'MANHUA', 'COMICS', 'WEBTOON', 'OTHER', name='titletype'), nullable=False),
    sa.Column('status', sa.Enum('ONGOING', 'FINISHED', 'DISCONTINUED', 'LICENSED', 'FROZEN', 'ANONS', 'UNKNOWN', name='titlestatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_quality_score', sa.Float(), nullable=False),
    sa.Column('primary_source', sa.Enum('MAL', 'SHIKIMORI', 'REMANGA', 'CUSTOM', name='source'), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('extended_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_titles_categories'), 'titles', ['categories'], unique=False)
    op.create_index('ix_titles_categories_gin', 'titles', ['categories'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_titles_chapters'), 'titles', ['chapters'], unique=False)
    op.create_index(op.f('ix_titles_data_quality_score'), 'titles', ['data_quality_score'], unique=False)
    op.create_index(op.f('ix_titles_ended_at'), 'titles', ['ended_at'], unique=False)
    op.create_index(op.f('ix_titles_genres'), 'titles', ['genres'], unique=False)
    op.create_index('ix_titles_genres_gin', 'titles', ['genres'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_titles_id'), 'titles', ['id'], unique=False)
    op.create_index(op.f('ix_titles_is_deleted'), 'titles', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_titles_is_manual'), 'titles', ['is_manual'], unique=False)
    op.create_index(op.f('ix_titles_mal_id'), 'titles', ['mal_id'], unique=True)
    op.create_index(op.f('ix_titles_popularity'), 'titles', ['popularity'], unique=False)
    op.create_index(op.f('ix_titles_rating'), 'titles', ['rating'], unique=False)
    op.create_index('ix_titles_rating_popularity', 'titles', ['rating', 'popularity'], unique=False)
    op.create_index(op.f('ix_titles_released_at'), 'titles', ['released_at'], unique=False)
    op.create_index(op.f('ix_titles_search_text'), 'titles', ['search_text'], unique=False)
    op.create_index('ix_titles_search_text_trgm', 'titles', ['search_text'], unique=False, postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    op.create_index('ix_titles_search_vector_gin', 'titles', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_titles_status'), 'titles', ['status'], unique=False)
    op.create_index('ix_titles_status_type', 'titles', ['status', 'type'], unique=False)
    op.create_index(op.f('ix_titles_type'), 'titles', ['type'], unique=False)
    op.create_index('ix_titles_type_released', 'titles', ['type', 'released_at'], unique=False)
    op.create_index(op.f('ix_titles_volumes'), 'titles', ['volumes'], unique=False)
    op.create_table('titles_raw_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('master_title_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.Enum('MAL', 'SHIKIMORI', 'REMANGA', 'CUSTOM', name='source'), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('consolidation_status', sa.Enum('PENDING', 'IN_PROGRESS', 'CONSOLIDATED', 'FAILED', name='consolidationstatus'), nullable=True),
    sa.Column('consolidation_detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extended_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['master_title_id'], ['titles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'external_id', name='uq_source_external_id')
    )
    op.create_index('idx_source_data_unmapped', 'titles_raw_data', ['master_title_id'], unique=False, postgresql_where=sa.text('master_title_id IS NULL'))
    op.create_index('ix_raw_consolidation_pending', 'titles_raw_data', ['consolidation_status', 'fetched_at'], unique=False, postgresql_where=sa.text("consolidation_status = 'PENDING'"))
    op.create_index('ix_raw_data_gin', 'titles_raw_data', ['raw_data'], unique=False, postgresql_using='gin')
    op.create_index('ix_raw_master_not_deleted', 'titles_raw_data', ['master_title_id', 'is_deleted'], unique=False, postgresql_where=sa.text('is_deleted = false'))
    op.create_index(op.f('ix_titles_raw_data_consolidation_status'), 'titles_raw_data', ['consolidation_status'], unique=False)
    op.create_index(op.f('ix_titles_raw_data_external_id'), 'titles_raw_data', ['external_id'], unique=False)
    op.create_index(op.f('ix_titles_raw_data_fetched_at'), 'titles_raw_data', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_titles_raw_data_id'), 'titles_raw_data', ['id'], unique=False)
    op.create_index(op.f('ix_titles_raw_data_is_deleted'), 'titles_raw_data', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_titles_raw_data_master_title_id'), 'titles_raw_data', ['master_title_id'], unique=False)
    op.create_index(op.f('ix_titles_raw_data_source'), 'titles_raw_data', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_titles_raw_data_source'), table_name='titles_raw_data')
    op.drop_index(op.f('ix_titles_raw_data_master_title_id'), table_name='titles_raw_data')
    op.drop_index(op.f('ix_titles_raw_data_is_deleted'), table_name='titles_raw_data')
    op.drop_index(op.f('ix_titles_raw_data_id'), table_name='titles_raw_data')
    op.drop_index(op.f('ix_titles_raw_data_fetched_at'), table_name='titles_raw_data')
    op.drop_index(op.f('ix_titles_raw_data_external_id'), table_name='titles_raw_data')
    op.drop_index(op.f('ix_titles_raw_data_consolidation_status'), table_name='titles_raw_data')
    op.drop_index('ix_raw_master_not_deleted', table_name='titles_raw_data', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_raw_data_gin', table_name='titles_raw_data', postgresql_using='gin')
    op.drop_index('ix_raw_consolidation_pending', table_name='titles_raw_data', postgresql_where=sa.text("consolidation_status = 'PENDING'"))
    op.drop_index('idx_source_data_unmapped', table_name='titles_raw_data', postgresql_where=sa.text('master_title_id IS NULL'))
    op.drop_table('titles_raw_data')
    op.drop_index(op.f('ix_titles_volumes'), table_name='titles')
    op.drop_index('ix_titles_type_released', table_name='titles')
    op.drop_index(op.f('ix_titles_type'), table_name='titles')
    op.drop_index('ix_titles_status_type', table_name='titles')
    op.drop_index(op.f('ix_titles_status'), table_name='titles')
    op.drop_index('ix_titles_search_vector_gin', table_name='titles', postgresql_using='gin')
    op.drop_index('ix_titles_search_text_trgm', table_name='titles', postgresql_using='gin', postgresql_ops={'search_text': 'gin_trgm_ops'})
    op.drop_index(op.f('ix_titles_search_text'), table_name='titles')
    op.drop_index(op.f('ix_titles_released_at'), table_name='titles')
    op.drop_index('ix_titles_rating_popularity', table_name='titles')
    op.drop_index(op.f('ix_titles_rating'), table_name='titles')
    op.drop_index(op.f('ix_titles_popularity'), table_name='titles')
    op.drop_index(op.f('ix_titles_mal_id'), table_name='titles')
    op.drop_index(op.f('ix_titles_is_manual'), table_name='titles')
    op.drop_index(op.f('ix_titles_is_deleted'), table_name='titles')
    op.drop_index(op.f('ix_titles_id'), table_name='titles')
    op.drop_index('ix_titles_genres_gin', table_name='titles', postgresql_using='gin')
    op.drop_index(op.f('ix_titles_genres'), table_name='titles')
    op.drop_index(op.f('ix_titles_ended_at'), table_name='titles')
    op.drop_index(op.f('ix_titles_data_quality_score'), table_name='titles')
    op.drop_index(op.f('ix_titles_chapters'), table_name='titles')
    op.drop_index('ix_titles_categories_gin', table_name='titles', postgresql_using='gin')
    op.drop_index(op.f('ix_titles_categories'), table_name='titles')
    op.drop_table('titles')
    # ### end Alembic commands ###
