"""remove_lecensed_status

Revision ID: cbc74fea7666
Revises: 4a6ff30a20a5
Create Date: 2026-05-08 22:59:43.400074

"""

from typing import Sequence, Union

import sqlmodel.sql.sqltypes
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cbc74fea7666"
down_revision: Union[str, Sequence[str], None] = "4a6ff30a20a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE titles SET status = 'ONGOING' WHERE status = 'LICENSED';")
    op.execute("""
        UPDATE titles_raw_data 
        SET data = jsonb_set(data, '{status}', '"ONGOING"', false)
        WHERE data->>'status' = 'LICENSED';
    """)
    op.execute("ALTER TYPE titlestatus RENAME TO titlestatus_old;")
    op.execute(
        "CREATE TYPE titlestatus AS ENUM('ONGOING', 'FINISHED', 'DISCONTINUED', 'FROZEN', 'ANONS', 'UNKNOWN');"
    )
    op.execute(
        "ALTER TABLE titles ALTER COLUMN status TYPE titlestatus USING status::text::titlestatus;"
    )
    op.execute("DROP TYPE titlestatus_old;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE titlestatus RENAME TO titlestatus_old;")
    op.execute(
        "CREATE TYPE titlestatus AS ENUM('ONGOING', 'FINISHED', 'DISCONTINUED', 'LICENSED', 'FROZEN', 'ANONS', 'UNKNOWN');"
    )
    op.execute(
        "ALTER TABLE titles ALTER COLUMN status TYPE titlestatus USING status::text::titlestatus;"
    )
    op.execute("DROP TYPE titlestatus_old;")
    # ### end Alembic commands ###
