"""add note field

Revision ID: de0d04f9eb90
Revises: f3f35145bea8_add_triggers
Create Date: 2026-02-13 15:24:50.584961

"""
from typing import Sequence, Union

import sqlmodel.sql.sqltypes
import sqlalchemy as sa

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'de0d04f9eb90'
down_revision: Union[str, Sequence[str], None] = 'f3f35145bea8_add_triggers'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_titles', sa.Column('note', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_titles', 'note')
    # ### end Alembic commands ###
